[package]
name = "db_wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
db = { path = "../db" }
rusqlite = { version = "0.40.2", features = ["bundled-full"] }
sqlite-wasm-rs = { version = "0.5", optional = true }
sqlite-wasm-vfs = { version = "0.2", optional = true }
wasm-bindgen = { version = "0.2.127", optional = true }
wasm-bindgen-futures = { version = "0.4.77", optional = true }

[features]
default = ["web"]
android = []
web = [
    "sqlite-wasm-rs",
    "sqlite-wasm-vfs",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
]

[lib]
crate-type = ["cdylib", "rlib"]
